### ISSUE TITLE
Set normalizeTags to false in index.js 

### ISSUE THREAD

**Issue by Deborah-Digges** [intuit/node-pom-parser#10]
Would it make sense to set normalizeTags to false in index.js, so that the resulting JSON object has keys that correspond exactly to the xml tag names?
For example, `artifactId` instead of `artifactid`.

**Comment by marcellodesales** [comment]
Hi @Deborah-Digges 

I completely agree that the behavior should not break the contract between the original document and the `JSON` object... However, can you verify what else would we lose with `normalizeTags`? I think there are other reasons why that method call was used initially...

**Comment by marcellodesales** [comment]
Will close due to the lack user feedback.
