### ISSUE TITLE
Fix dependabot alert

### ISSUE THREAD

**Issue by nsinghal12** [intuit/node-pom-parser#19]
Current alert reports an error in Apache Tapestry pom.xml that we use as a test fixture. Need to fix that.

**Comment by foobar98** [comment]
@nsinghal12 Where can I see this dependabot alert? I believe I may not have access.

**Comment by mkm1997** [comment]
@nsinghal12 can you please elaborate the problem statement

**Comment by nsinghal12** [comment]
Assigning this to @mkm1997 to provide fair share as part of Intuit's hacktoberfest.
