### ISSUE TITLE
Use import syntax instead of require to allow generation of ESM

### ISSUE THREAD

**Issue by nsinghal12** [intuit/node-pom-parser#20]

**Comment by foobar98** [comment]
@nsinghal12 Can this be assigned to me please?

**Comment by Kunalbhandari** [comment]
@nsinghal12 could you help me on this one ?

**Comment by nsinghal12** [comment]
Assigning this to @Kunalbhandari to provide fair share as part of Intuit's hacktoberfest.

**Comment by nsinghal12** [comment]
Closing the issue as this has been fixed via #34
