### ISSUE TITLE
Convert code to Typescript

### ISSUE THREAD

**Issue by nsinghal12** [intuit/node-pom-parser#28]
This will allow us to make use of `interface`s to bring type-safety and object completion for parsed JS object in editors.

**Comment by nsinghal12** [comment]
thanks for expressing your interest. I assigned it to you. @aabhas-sao

**Comment by nsinghal12** [comment]
Hi Folks, This issue is still open. Please comment on this if anyone wants to work on it and I can re-assign. Thanks!

**Comment by Tanmay-21** [comment]
Hi @nsinghal12 Could you assign this to me please
