### ISSUE TITLE
Add another method `async parseAsync` that does not use callback

### ISSUE THREAD

**Issue by nsinghal12** [intuit/node-pom-parser#30]
Remove the need of passing a callback and change code to use `parse` method.

**Comment by ShubhamVyas-1994** [comment]
Hi,
Can you assign the ticket to me ?

**Comment by thejsdeveloper** [comment]
Hi @nsinghal12 

Can you explain bit more ?
So the requirement here is we will not accept callback any more ? I can see callback is called at multiple places in parse method.

**Comment by nsinghal12** [comment]
Assigning it to @ShubhamVyas-1994 as he asked first. Thanks for volunteering.

**Comment by thejsdeveloper** [comment]
@nsinghal12 Thanks :) Yes he can take the issue. 

I wanted to confirm the behaviour. What will happen to existing consumers if we remove the callback ?

Should it be backward compatible ?

**Comment by nsinghal12** [comment]
@thejsdeveloper good point. 
@ShubhamVyas-1994 let's add another method that exposes `async` way than removing it. Also, mark the existing method deprecated. This way we can remove it in our next major bump up.
