### ISSUE TITLE
'util' is defined but never used.

### ISSUE THREAD

**Issue by marcellodesales** [intuit/node-pom-parser#4]
#### Occurred on:
+ **Commit**:  abe986e4c7797df88dcb3917684a8ec0dc506f8e
+ **File**:    [lib/index.js](https://github.com/marcellodesales/node-pom-parser/blob/abe986e4c7797df88dcb3917684a8ec0dc506f8e/lib/index.js)
+ **LineNum**: [7](https://github.com/marcellodesales/node-pom-parser/blob/abe986e4c7797df88dcb3917684a8ec0dc506f8e/lib/index.js#L7)
+ **Code**:    `var util = require('util')`

    
#### Currently on:
+ **Commit**:  0100456fe59caa8345fb36598a2127361fd67977
+ **File**:    [lib/index.js](https://github.com/marcellodesales/node-pom-parser/blob/0100456fe59caa8345fb36598a2127361fd67977/lib/index.js)
+ **LineNum**: [8](https://github.com/marcellodesales/node-pom-parser/blob/0100456fe59caa8345fb36598a2127361fd67977/lib/index.js#L8)

**Comment by runderworld** [comment]
Close this as fixed?

**Comment by marcellodesales** [comment]
@runderworld 👍
