### ISSUE TITLE
Coveralls dependency must move to the devDependencies

### ISSUE THREAD

**Issue by marcellodesales** [intuit/node-pom-parser#7]
The `coveralls` dependency was installed under the runtime dependencies. 

https://github.com/intuit/node-pom-parser/blob/master/package.json#L17

It must be under dev dependencies:

```
npm install --save-dev coveralls
```

**Comment by runderworld** [comment]
Close this as fixed?

**Comment by marcellodesales** [comment]
@runderworld DONE!
